name: Check for Updates
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # daily at 00:00 UTC

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - run: npm run check
